# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ReactJs CI/CD

on:
  push:
    branches: [ deploy ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd reactNinjaSecondPart
    - run: npm i
    - run: npm run build 
    - run: cd build
    - run: sudo rm -rf /var/www/html/react
    - run: sudo mkdir /var/www/html/react
    - run: sudo cp -R . /var/www/html/react

